[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
one_cs = "2hbskEy4Ds4Khg1FFL1firEpnYLnvkhFeM4PzH9eoabg"

[programs.localnet]
one_cs = "2hbskEy4Ds4Khg1FFL1firEpnYLnvkhFeM4PzH9eoabg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
